repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--config=./terraform/.terraform-docs.yaml
      - id: terraform_tflint
      - id: terraform_checkov
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.12.2
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible
  - repo: https://github.com/stanleyz/pre-commit-packer
    rev: feat/pushd-issue
    hooks:
      - id: packer_fmt
      - id: packer_validate
